Django_MVC_video/mywebsite/music/urls.py
from django.urls import path
from . import views

#app_name = 'music'

urlpatterns = [
    # /music/
    path('', views.index, name="index"),
    # /music/a_number/
    path('<int:album_id>/', views.detail, name='detail'),
]

Django_MVC_video/mywebsite/mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls'))
]

Django_MVC_video/mywebsite/music/models.py
from django.db import models

# Create your models here.

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=250)
    genre = models.CharField(max_length=250)
    album_logo = models.CharField(max_length=250)

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    song_title = models.CharField(max_length=250)
    file_type = models.CharField(max_length=250)

    def __str__(self):
        return self.song_title

Django_MVC_video/mywebsite/music/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from .models import Album
from django.template import loader

# Create your views here.

def index(request):
    all_albums = Album.objects.all()
    template = 'music/index.html'
    context = {
        'all_albums':all_albums
    }
    return render(request, template, context)

def detail(request, album_id):
    try:
        album = Album.objects.get(pk=album_id)
    except Album.DoesNotExist:
        raise Http404("Album does not exist")
    return render(request, 'music/detail.html', {'album': album})

Django_MVC_video/mywebsite/music/templates/music/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Album</title>
</head>
<body>

<img src="{{ album.album_logo }}">

<h1>{{ album.album_title }}</h1>
<h2>{{ album.artist }}</h2>

<ul>
    {% for song in album.song_set.all %}
    <li>{{ song.song_title }} - {{song.file_type }}</li>
    {% endfor %}
</ul>


</body>
</html>

Django_MVC_video/mywebsite/music/templates/music/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Music</title>
</head>
<body>
<h2> Here are all my albums </h2>
        <ul>
            {% for album in all_albums %}
            <li><a href="{% url 'detail' album.id %}">{{ album.album_title }}</a></li>
            {% endfor %}
        </ul>

</body>
</html>